# site settings
title: Gurshaant Malik
subtitle: 
email: garymalik8080@gmail.com
description: The personal webpage of Gurshaant Malik.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gsmalik.github.io" # the base hostname & protocol for your site
author: Gurshaant Malik
street_address: Unit 103, 255 Sunview Street 
city: Waterloo
state: Ontario
zip_code: N2L 3V8
country: Canada
phone: (519) 781-4647

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
github_url: https://github.com/gsmalik
linkedin_url: https://www.linkedin.com/in/gurshaantmalik/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
